<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (machine+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT machine (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, port*, adjuster*, driver?, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine isbios (yes|no) "no">
		<!ATTLIST machine isdevice (yes|no) "no">
		<!ATTLIST machine ismechanical (yes|no) "no">
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT device_ref EMPTY>
			<!ATTLIST device_ref name CDATA #REQUIRED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display tag CDATA #IMPLIED>
			<!ATTLIST display type (raster|vector|lcd|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #REQUIRED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input buttons CDATA #IMPLIED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
				<!ATTLIST control ways CDATA #IMPLIED>
				<!ATTLIST control ways2 CDATA #IMPLIED>
				<!ATTLIST control ways3 CDATA #IMPLIED>
		<!ELEMENT dipswitch (dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT dipvalue EMPTY>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT confsetting EMPTY>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT port (analog*)>
			<!ATTLIST port tag CDATA #REQUIRED>
			<!ELEMENT analog EMPTY>
				<!ATTLIST analog mask CDATA #REQUIRED>
		<!ELEMENT adjuster EMPTY>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver graphic (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver protection (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
		<!ELEMENT device (instance*, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption devname CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
			<!ATTLIST softwarelist filter CDATA #IMPLIED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.170 (Jun 16 2016)" debug="no" mameconfig="10">
	<machine name="neogeo" sourcefile="neogeo.cpp" isbios="yes">
		<description>Neo-Geo</description>
		<year>1990</year>
		<manufacturer>SNK</manufacturer>
		<biosset name="euro" description="Europe MVS (Ver. 2)" default="yes"/>
		<biosset name="euro-s1" description="Europe MVS (Ver. 1)"/>
		<biosset name="us" description="US MVS (Ver. 2?)"/>
		<biosset name="us-e" description="US MVS (Ver. 1)"/>
		<biosset name="us-v2" description="US MVS (4 slot, Ver 2)"/>
		<biosset name="asia" description="Asia MVS (Ver. 3)"/>
		<biosset name="japan" description="Japan MVS (Ver. 3)"/>
		<biosset name="japan-s2" description="Japan MVS (Ver. 2)"/>
		<biosset name="japan-s1" description="Japan MVS (Ver. 1)"/>
		<biosset name="mv1c" description="NEO-MVH MV1C"/>
		<biosset name="japan-j3" description="Japan MVS (J3)"/>
		<biosset name="japan-hotel" description="Custom Japanese Hotel"/>
		<biosset name="unibios31" description="Universe Bios (Hack, Ver. 3.1)"/>
		<biosset name="unibios30" description="Universe Bios (Hack, Ver. 3.0)"/>
		<biosset name="unibios23" description="Universe Bios (Hack, Ver. 2.3)"/>
		<biosset name="unibios23o" description="Universe Bios (Hack, Ver. 2.3, older?)"/>
		<biosset name="unibios22" description="Universe Bios (Hack, Ver. 2.2)"/>
		<biosset name="unibios21" description="Universe Bios (Hack, Ver. 2.1)"/>
		<biosset name="unibios20" description="Universe Bios (Hack, Ver. 2.0)"/>
		<biosset name="unibios13" description="Universe Bios (Hack, Ver. 1.3)"/>
		<biosset name="unibios12" description="Universe Bios (Hack, Ver. 1.2)"/>
		<biosset name="unibios12o" description="Universe Bios (Hack, Ver. 1.2, older)"/>
		<biosset name="unibios11" description="Universe Bios (Hack, Ver. 1.1)"/>
		<biosset name="unibios10" description="Universe Bios (Hack, Ver. 1.0)"/>
		<rom name="sp-s2.sp1" bios="euro" size="131072" crc="9036d879" sha1="4f5ed7105b7128794654ce82b51723e16e389543" region="mainbios" offset="0"/>
		<rom name="sp-s.sp1" bios="euro-s1" size="131072" crc="c7f2fa45" sha1="09576ff20b4d6b365e78e6a5698ea450262697cd" region="mainbios" offset="0"/>
		<rom name="sp-u2.sp1" bios="us" size="131072" crc="e72943de" sha1="5c6bba07d2ec8ac95776aa3511109f5e1e2e92eb" region="mainbios" offset="0"/>
		<rom name="sp-e.sp1" bios="us-e" size="131072" crc="2723a5b5" sha1="5dbff7531cf04886cde3ef022fb5ca687573dcb8" region="mainbios" offset="0"/>
		<rom name="v2.bin" bios="us-v2" size="131072" crc="62f021f4" sha1="62d372269e1b3161c64ae21123655a0a22ffd1bb" region="mainbios" offset="0"/>
		<rom name="asia-s3.rom" bios="asia" size="131072" crc="91b64be3" sha1="720a3e20d26818632aedf2c2fd16c54f213543e1" region="mainbios" offset="0"/>
		<rom name="vs-bios.rom" bios="japan" size="131072" crc="f0e8f27d" sha1="ecf01eda815909f1facec62abf3594eaa8d11075" region="mainbios" offset="0"/>
		<rom name="sp-j2.sp1" bios="japan-s2" size="131072" crc="acede59c" sha1="b6f97acd282fd7e94d9426078a90f059b5e9dd91" region="mainbios" offset="0"/>
		<rom name="sp1.jipan.1024" bios="japan-s1" size="131072" crc="9fb0abe4" sha1="18a987ce2229df79a8cf6a84f968f0e42ce4e59d" region="mainbios" offset="0"/>
		<rom name="sp-45.sp1" bios="mv1c" size="524288" crc="03cc9f6a" sha1="cdf1f49e3ff2bac528c21ed28449cf35b7957dc1" region="mainbios" offset="0"/>
		<rom name="japan-j3.bin" bios="japan-j3" size="131072" crc="dff6d41f" sha1="e92910e20092577a4523a6b39d578a71d4de7085" region="mainbios" offset="0"/>
		<rom name="sp-1v1_3db8c.bin" bios="japan-hotel" size="131072" crc="162f0ebe" sha1="fe1c6dd3dfcf97d960065b1bb46c1e11cb7bf271" region="mainbios" offset="0"/>
		<rom name="uni-bios_3_1.rom" bios="unibios31" size="131072" crc="0c58093f" sha1="29329a3448c2505e1ff45ffa75e61e9693165153" region="mainbios" offset="0"/>
		<rom name="uni-bios_3_0.rom" bios="unibios30" size="131072" crc="a97c89a9" sha1="97a5eff3b119062f10e31ad6f04fe4b90d366e7f" region="mainbios" offset="0"/>
		<rom name="uni-bios_2_3.rom" bios="unibios23" size="131072" crc="27664eb5" sha1="5b02900a3ccf3df168bdcfc98458136fd2b92ac0" region="mainbios" offset="0"/>
		<rom name="uni-bios_2_3o.rom" bios="unibios23o" size="131072" crc="601720ae" sha1="1b8a72c720cdb5ee3f1d735bbcf447b09204b8d9" region="mainbios" offset="0"/>
		<rom name="uni-bios_2_2.rom" bios="unibios22" size="131072" crc="2d50996a" sha1="5241a4fb0c63b1a23fd1da8efa9c9a9bd3b4279c" region="mainbios" offset="0"/>
		<rom name="uni-bios_2_1.rom" bios="unibios21" size="131072" crc="8dabf76b" sha1="c23732c4491d966cf0373c65c83c7a4e88f0082c" region="mainbios" offset="0"/>
		<rom name="uni-bios_2_0.rom" bios="unibios20" size="131072" crc="0c12c2ad" sha1="37bcd4d30f3892078b46841d895a6eff16dc921e" region="mainbios" offset="0"/>
		<rom name="uni-bios_1_3.rom" bios="unibios13" size="131072" crc="b24b44a0" sha1="eca8851d30557b97c309a0d9f4a9d20e5b14af4e" region="mainbios" offset="0"/>
		<rom name="uni-bios_1_2.rom" bios="unibios12" size="131072" crc="4fa698e9" sha1="682e13ec1c42beaa2d04473967840c88fd52c75a" region="mainbios" offset="0"/>
		<rom name="uni-bios_1_2o.rom" bios="unibios12o" size="131072" crc="e19d3ce9" sha1="af88ef837f44a3af2d7144bb46a37c8512b67770" region="mainbios" offset="0"/>
		<rom name="uni-bios_1_1.rom" bios="unibios11" size="131072" crc="5dda0d84" sha1="4153d533c02926a2577e49c32657214781ff29b7" region="mainbios" offset="0"/>
		<rom name="uni-bios_1_0.rom" bios="unibios10" size="131072" crc="0ce453a0" sha1="3b4c0cd26c176fc6b26c3a2f95143dd478f6abf9" region="mainbios" offset="0"/>
		<rom name="sm1.sm1" size="131072" crc="94416d67" sha1="42f9d7ddd6c0931fd64226a60dc73602b2819dcf" region="audiobios" offset="0"/>
		<rom name="sm1.sm1" size="131072" crc="94416d67" sha1="42f9d7ddd6c0931fd64226a60dc73602b2819dcf" region="audiocpu" offset="0"/>
		<rom name="000-lo.lo" size="131072" crc="5a86cff2" sha1="5992277debadeb64d1c1c64b0a92d9293eaf7e4a" region="zoomy" offset="0"/>
		<rom name="sfix.sfix" size="131072" crc="c2ea0cfd" sha1="fd4a618cdcdbf849374f0a50dd8efe9dbab706c3" region="fixedbios" offset="0"/>
		<device_ref name="m68000"/>
		<device_ref name="z80"/>
		<device_ref name="screen"/>
		<device_ref name="palette"/>
		<device_ref name="neosprite"/>
		<device_ref name="speaker"/>
		<device_ref name="speaker"/>
		<device_ref name="ym2610"/>
		<device_ref name="neogeo_banked_cart"/>
		<device_ref name="upd4990a"/>
		<device_ref name="nvram"/>
		<device_ref name="ng_memcard"/>
		<device_ref name="neogeo_cart_slot"/>
		<device_ref name="neogeo_cart_slot"/>
		<device_ref name="neogeo_cart_slot"/>
		<device_ref name="neogeo_cart_slot"/>
		<device_ref name="neogeo_cart_slot"/>
		<device_ref name="neogeo_cart_slot"/>
		<device_ref name="software_list"/>
		<chip type="cpu" tag="maincpu" name="M68000" clock="12000000"/>
		<chip type="cpu" tag="audiocpu" name="Z80" clock="4000000"/>
		<chip type="audio" tag="lspeaker" name="Speaker"/>
		<chip type="audio" tag="rspeaker" name="Speaker"/>
		<chip type="audio" tag="ymsnd" name="YM2610" clock="8000000"/>
		<display tag="screen" type="raster" rotate="0" width="320" height="224" refresh="59.185606" pixclock="6000000" htotal="384" hbend="30" hbstart="350" vtotal="264" vbend="16" vbstart="240" />
		<sound channels="2"/>
		<input players="2" buttons="4" coins="4" service="yes">
			<control type="joy" ways="8"/>
		</input>
		<dipswitch name="Setting Mode" tag="P1/DSW" mask="1">
			<dipvalue name="Off" value="1" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Cabinet" tag="P1/DSW" mask="2">
			<dipvalue name="Normal" value="2" default="yes"/>
			<dipvalue name="VS Mode" value="0"/>
		</dipswitch>
		<dipswitch name="Controller" tag="P1/DSW" mask="4">
			<dipvalue name="Joystick" value="4" default="yes"/>
			<dipvalue name="Mahjong Panel" value="0"/>
		</dipswitch>
		<dipswitch name="COMM Setting (Cabinet No.)" tag="P1/DSW" mask="24">
			<dipvalue name="1" value="24" default="yes"/>
			<dipvalue name="2" value="16"/>
			<dipvalue name="3" value="8"/>
			<dipvalue name="4" value="0"/>
		</dipswitch>
		<dipswitch name="COMM Setting (Link Enable)" tag="P1/DSW" mask="32">
			<dipvalue name="Off" value="32" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Free Play" tag="P1/DSW" mask="64">
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Freeze" tag="P1/DSW" mask="128">
			<dipvalue name="Off" value="128" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<port tag=":P1/DSW">
		</port>
		<port tag=":P2">
		</port>
		<port tag=":SYSTEM">
		</port>
		<port tag=":AUDIO/COIN">
		</port>
		<port tag=":TEST">
		</port>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="supported"/>
		<device type="memcard" tag="memcard">
			<instance name="memcard" briefname="memc"/>
			<extension name="neo"/>
		</device>
		<device type="cartridge" tag="cartslot1" interface="neo_cart">
			<instance name="cartridge1" briefname="cart1"/>
			<extension name="bin"/>
		</device>
		<device type="cartridge" tag="cartslot2" interface="neo_cart">
			<instance name="cartridge2" briefname="cart2"/>
			<extension name="bin"/>
		</device>
		<device type="cartridge" tag="cartslot3" interface="neo_cart">
			<instance name="cartridge3" briefname="cart3"/>
			<extension name="bin"/>
		</device>
		<device type="cartridge" tag="cartslot4" interface="neo_cart">
			<instance name="cartridge4" briefname="cart4"/>
			<extension name="bin"/>
		</device>
		<device type="cartridge" tag="cartslot5" interface="neo_cart">
			<instance name="cartridge5" briefname="cart5"/>
			<extension name="bin"/>
		</device>
		<device type="cartridge" tag="cartslot6" interface="neo_cart">
			<instance name="cartridge6" briefname="cart6"/>
			<extension name="bin"/>
		</device>
		<slot name="cartslot1">
		</slot>
		<slot name="cartslot2">
		</slot>
		<slot name="cartslot3">
		</slot>
		<slot name="cartslot4">
		</slot>
		<slot name="cartslot5">
		</slot>
		<slot name="cartslot6">
		</slot>
		<softwarelist name="neogeo" status="original" />
	</machine>
	<machine name="m68000" sourcefile="src/devices/cpu/m68000/m68kcpu.cpp" isdevice="yes" runnable="no">
		<description>M68000</description>
	</machine>
	<machine name="z80" sourcefile="src/devices/cpu/z80/z80.cpp" isdevice="yes" runnable="no">
		<description>Z80</description>
	</machine>
	<machine name="screen" sourcefile="src/emu/screen.cpp" isdevice="yes" runnable="no">
		<description>Video Screen</description>
	</machine>
	<machine name="palette" sourcefile="src/emu/emupal.cpp" isdevice="yes" runnable="no">
		<description>palette</description>
	</machine>
	<machine name="neosprite" sourcefile="src/mame/video/neogeo_spr.cpp" isdevice="yes" runnable="no">
		<description>Neogeo Sprites</description>
	</machine>
	<machine name="speaker" sourcefile="src/emu/speaker.cpp" isdevice="yes" runnable="no">
		<description>Speaker</description>
		<sound channels="1"/>
	</machine>
	<machine name="ym2610" sourcefile="src/devices/sound/2610intf.cpp" isdevice="yes" runnable="no">
		<description>YM2610</description>
		<sound channels="0"/>
	</machine>
	<machine name="neogeo_banked_cart" sourcefile="src/devices/bus/neogeo/banked_cart.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Banked Cartridge</description>
	</machine>
	<machine name="upd4990a" sourcefile="src/devices/machine/upd1990a.cpp" isdevice="yes" runnable="no">
		<description>uPD4990A RTC</description>
	</machine>
	<machine name="nvram" sourcefile="src/devices/machine/nvram.cpp" isdevice="yes" runnable="no">
		<description>NVRAM</description>
	</machine>
	<machine name="ng_memcard" sourcefile="src/mame/machine/ng_memcard.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Memory Card</description>
	</machine>
	<machine name="neogeo_cart_slot" sourcefile="src/devices/bus/neogeo/neogeo_slot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Cartridge Slot</description>
	</machine>
	<machine name="software_list" sourcefile="src/emu/softlist.cpp" isdevice="yes" runnable="no">
		<description>Software list</description>
	</machine>
	<machine name="neogeo_rom" sourcefile="src/devices/bus/neogeo/rom.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO ROM Carts</description>
	</machine>
	<machine name="mslugx_prot" sourcefile="src/devices/bus/neogeo/mslugx_prot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Protection (Metal Slug X)</description>
	</machine>
	<machine name="fatfury2_prot" sourcefile="src/devices/bus/neogeo/fatfury2_prot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Protection (Fatal Fury 2)</description>
	</machine>
	<machine name="kof98_prot" sourcefile="src/devices/bus/neogeo/kof98_prot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Protection (KOF98)</description>
	</machine>
	<machine name="sma_prot" sourcefile="src/devices/bus/neogeo/sma_prot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo SMA Cartridge</description>
	</machine>
	<machine name="cmc_prot" sourcefile="src/devices/bus/neogeo/cmc_prot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Protection (CMC)</description>
	</machine>
	<machine name="sma_kof99_cart" sourcefile="src/devices/bus/neogeo/sma_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO SMA Kof99 Cart</description>
	</machine>
	<machine name="sma_garou_cart" sourcefile="src/devices/bus/neogeo/sma_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO SMA Garou Cart</description>
	</machine>
	<machine name="sma_garouh_cart" sourcefile="src/devices/bus/neogeo/sma_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO SMA Garou (alt) Cart</description>
	</machine>
	<machine name="sma_mslug3_cart" sourcefile="src/devices/bus/neogeo/sma_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO SMA Mslug3 Cart</description>
	</machine>
	<machine name="sma_kof2000_cart" sourcefile="src/devices/bus/neogeo/sma_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO SMA KOF2000 Cart</description>
	</machine>
	<machine name="cmc_zupapa_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC zupapa Cart</description>
	</machine>
	<machine name="cmc_mslug3h_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC mslug3h Cart</description>
	</machine>
	<machine name="cmc_ganryu_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC ganryu Cart</description>
	</machine>
	<machine name="cmc_s1945p_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC s1945p Cart</description>
	</machine>
	<machine name="cmc_preisle2_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC preisle2 Cart</description>
	</machine>
	<machine name="cmc_bangbead_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC bangbead Cart</description>
	</machine>
	<machine name="cmc_nitd_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC nitd Cart</description>
	</machine>
	<machine name="cmc_sengoku3_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC sengoku3 Cart</description>
	</machine>
	<machine name="cmc_kof99k_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC kof99k Cart</description>
	</machine>
	<machine name="cmc_kof2001_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC kof2001 Cart</description>
	</machine>
	<machine name="cmc_kof2000n_cart" sourcefile="src/devices/bus/neogeo/cmc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO CMC kof2000n Cart</description>
	</machine>
	<machine name="p2_mslug4_cart" sourcefile="src/devices/bus/neogeo/pcm2_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO PCM2 mslug4 Cart</description>
	</machine>
	<machine name="pcm2_prot" sourcefile="src/devices/bus/neogeo/pcm2_prot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Protection (NEOPCM2)</description>
	</machine>
	<machine name="p2_rotd_cart" sourcefile="src/devices/bus/neogeo/pcm2_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO PCM2 rotd Cart</description>
	</machine>
	<machine name="p2_pnyaa_cart" sourcefile="src/devices/bus/neogeo/pcm2_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO PCM2 pnyaa Cart</description>
	</machine>
	<machine name="p2_ms4plus_cart" sourcefile="src/devices/bus/neogeo/pcm2_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO PCM2 ms4plus Cart</description>
	</machine>
	<machine name="k2k_k2k_cart" sourcefile="src/devices/bus/neogeo/kof2002_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO Kof2002-type kof2002 Cart</description>
	</machine>
	<machine name="kof2002_prot" sourcefile="src/devices/bus/neogeo/kof2002_prot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Protection (KOF2002)</description>
	</machine>
	<machine name="k2k_matrim_cart" sourcefile="src/devices/bus/neogeo/kof2002_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO Kof2002-type matrim Cart</description>
	</machine>
	<machine name="k2k_ss5_cart" sourcefile="src/devices/bus/neogeo/kof2002_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO Kof2002-type Samsho5 Cart</description>
	</machine>
	<machine name="k2k_ss5s_cart" sourcefile="src/devices/bus/neogeo/kof2002_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO Kof2002-type Samsho5sp Cart</description>
	</machine>
	<machine name="k2k_k2kpls_cart" sourcefile="src/devices/bus/neogeo/kof2002_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO Kof2002-type kof2002plus Cart</description>
	</machine>
	<machine name="p2_mslug5_cart" sourcefile="src/devices/bus/neogeo/pvc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO PCM2 mslug5 Cart</description>
	</machine>
	<machine name="pvc_prot" sourcefile="src/devices/bus/neogeo/pvc_prot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Protection (PVC)</description>
	</machine>
	<machine name="p2_svc_cart" sourcefile="src/devices/bus/neogeo/pvc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO PCM2 svc Cart</description>
	</machine>
	<machine name="p2_kof2003_cart" sourcefile="src/devices/bus/neogeo/pvc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO PCM2 kof2003 Cart</description>
	</machine>
	<machine name="p2_kof2003h_cart" sourcefile="src/devices/bus/neogeo/pvc_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO PCM2 kof2003h Cart</description>
	</machine>
	<machine name="boot_garoubl_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT garoubl Cart</description>
	</machine>
	<machine name="ngbootleg_prot" sourcefile="src/devices/bus/neogeo/bootleg_prot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Protection (Bootleg)</description>
	</machine>
	<machine name="boot_cthd2003_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT cthd2003 Cart</description>
	</machine>
	<machine name="boot_ct2k3sp_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT ct2k3sp Cart</description>
	</machine>
	<machine name="boot_ct2k3sa_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT ct2k3sa Cart</description>
	</machine>
	<machine name="boot_kf10thep_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT kf10thep Cart</description>
	</machine>
	<machine name="boot_kf2k5uni_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT kf2k5uni Cart</description>
	</machine>
	<machine name="boot_kf2k4se_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT kf2k4se Cart</description>
	</machine>
	<machine name="boot_svcplus_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT svcplus Cart</description>
	</machine>
	<machine name="boot_svcplusa_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT svcplusa Cart</description>
	</machine>
	<machine name="boot_samsho5b_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT samsho5b Cart</description>
	</machine>
	<machine name="boot_kof97oro_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT kof97oro Cart</description>
	</machine>
	<machine name="boot_lans2004_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT lans2004 Cart</description>
	</machine>
	<machine name="boot_kof10th_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT kof10th Cart</description>
	</machine>
	<machine name="boot_kog_cart" sourcefile="src/devices/bus/neogeo/bootleg_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT kog Cart</description>
		<dipswitch name="Title Language" tag=":kog_prot:JUMPER" mask="1">
			<dipvalue name="English" value="1" default="yes"/>
			<dipvalue name="Non-English" value="0"/>
		</dipswitch>
	</machine>
	<machine name="kog_prot" sourcefile="src/devices/bus/neogeo/kog_prot.cpp" isdevice="yes" runnable="no">
		<description>NeoGeo Protection (King of Gladiator)</description>
		<dipswitch name="Title Language" tag=":JUMPER" mask="1">
			<dipvalue name="English" value="1" default="yes"/>
			<dipvalue name="Non-English" value="0"/>
		</dipswitch>
	</machine>
	<machine name="boot_mslug3b6_cart" sourcefile="src/devices/bus/neogeo/bootleg_hybrid_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT mslug3b6 Cart</description>
	</machine>
	<machine name="boot_kof2002b_cart" sourcefile="src/devices/bus/neogeo/bootleg_hybrid_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT kof2002b Cart</description>
	</machine>
	<machine name="boot_kf2k2mp_cart" sourcefile="src/devices/bus/neogeo/bootleg_hybrid_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT kf2k2mp Cart</description>
	</machine>
	<machine name="boot_kf2k2mp2_cart" sourcefile="src/devices/bus/neogeo/bootleg_hybrid_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT kf2k2mp2 Cart</description>
	</machine>
	<machine name="boot_matrimbl_cart" sourcefile="src/devices/bus/neogeo/bootleg_hybrid_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT matrimbl Cart</description>
	</machine>
	<machine name="boot_ms5plus_cart" sourcefile="src/devices/bus/neogeo/bootleg_hybrid_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT ms5plus Cart</description>
	</machine>
	<machine name="boot_svcboot_cart" sourcefile="src/devices/bus/neogeo/bootleg_hybrid_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT svcboot Cart</description>
	</machine>
	<machine name="boot_svcsplus_cart" sourcefile="src/devices/bus/neogeo/bootleg_hybrid_cart.cpp" isdevice="yes" runnable="no">
		<description>NEOGEO BOOT svcsplus Cart</description>
	</machine>
	<machine name="boot_kf2k3bl_cart" sourcefile="src/devices/bus/neogeo/bootleg_hybrid_cart.cpp" isdevice="yes" runnable="no">