<?xml version="1.0"?>
<!DOCTYPE softwarelists [
<!ELEMENT softwarelists (softwarelist*)>
	<!ELEMENT softwarelist (software+)>
		<!ATTLIST softwarelist name CDATA #REQUIRED>
		<!ATTLIST softwarelist description CDATA #IMPLIED>
		<!ELEMENT software (description, year, publisher, info*, sharedfeat*, part*)>
			<!ATTLIST software name CDATA #REQUIRED>
			<!ATTLIST software cloneof CDATA #IMPLIED>
			<!ATTLIST software supported (yes|partial|no) "yes">
			<!ELEMENT description (#PCDATA)>
			<!ELEMENT year (#PCDATA)>
			<!ELEMENT publisher (#PCDATA)>
			<!ELEMENT info EMPTY>
				<!ATTLIST info name CDATA #REQUIRED>
				<!ATTLIST info value CDATA #IMPLIED>
			<!ELEMENT sharedfeat EMPTY>
				<!ATTLIST sharedfeat name CDATA #REQUIRED>
				<!ATTLIST sharedfeat value CDATA #IMPLIED>
			<!ELEMENT part (feature*, dataarea*, diskarea*, dipswitch*)>
				<!ATTLIST part name CDATA #REQUIRED>
				<!ATTLIST part interface CDATA #REQUIRED>
				<!ELEMENT feature EMPTY>
					<!ATTLIST feature name CDATA #REQUIRED>
					<!ATTLIST feature value CDATA #IMPLIED>
				<!ELEMENT dataarea (rom*)>
					<!ATTLIST dataarea name CDATA #REQUIRED>
					<!ATTLIST dataarea size CDATA #REQUIRED>
					<!ATTLIST dataarea databits (8|16|32|64) "8">
					<!ATTLIST dataarea endian (big|little) "little">
					<!ELEMENT rom EMPTY>
						<!ATTLIST rom name CDATA #IMPLIED>
						<!ATTLIST rom size CDATA #IMPLIED>
						<!ATTLIST rom length CDATA #IMPLIED>
						<!ATTLIST rom crc CDATA #IMPLIED>
						<!ATTLIST rom sha1 CDATA #IMPLIED>
						<!ATTLIST rom offset CDATA #IMPLIED>
						<!ATTLIST rom value CDATA #IMPLIED>
						<!ATTLIST rom status (baddump|nodump|good) "good">
						<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue|reload_plain) #IMPLIED>
				<!ELEMENT diskarea (disk*)>
					<!ATTLIST diskarea name CDATA #REQUIRED>
					<!ELEMENT disk EMPTY>
						<!ATTLIST disk name CDATA #REQUIRED>
						<!ATTLIST disk sha1 CDATA #IMPLIED>
						<!ATTLIST disk status (baddump|nodump|good) "good">
						<!ATTLIST disk writeable (yes|no) "no">
				<!ELEMENT dipswitch (dipvalue*)>
					<!ATTLIST dipswitch name CDATA #REQUIRED>
					<!ATTLIST dipswitch tag CDATA #REQUIRED>
					<!ATTLIST dipswitch mask CDATA #REQUIRED>
					<!ELEMENT dipvalue EMPTY>
						<!ATTLIST dipvalue name CDATA #REQUIRED>
						<!ATTLIST dipvalue value CDATA #REQUIRED>
						<!ATTLIST dipvalue default (yes|no) "no">
]>

<softwarelists>
	<softwarelist name="segacd" description="Sega CD CD-ROMs">
		<software name="advbatr">
			<description>The Adventures of Batman and Robin (USA)</description>
			<year>1995</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4432"/>
			<info name="ring_code" value="1008604432 7/95 1RA2"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="adventures of batman and robin, the (usa)" sha1="80e65ec95ea9440e59d64ea067b48921686006e8" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="ah3ts">
			<description>AH3 - ThunderStrike (USA)</description>
			<year>1993</year>
			<publisher>JVC</publisher>
			<info name="serial" value="T-60055"/>
			<info name="ring_code" value="SEGAT60055RE R2D MFD BY JVC, SEGAT60055 R1D MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="ah3 - thunderstrike (usa)" sha1="46d352674119dabf0728a07dc7354b54fe5a027b" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="btlcorps">
			<description>Battlecorps (USA)</description>
			<year>1994</year>
			<publisher>Core Design</publisher>
			<info name="serial" value="T-115045"/>
			<info name="ring_code" value="SEGAT115045 R1H MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="battlecorps (usa)" sha1="6ea60ddc9064f7aa770ea87f2fb2ff438793c037" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="billwlsh">
			<description>Bill Walsh College Football (USA)</description>
			<year>1993</year>
			<publisher>Electronic Arts</publisher>
			<info name="serial" value="T-50025"/>
			<info name="ring_code" value="SEGAT115045 R1H MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="bill walsh college football (usa)" sha1="07cc70df34df37f25d24ea387205640dae48e31c" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="dracula">
			<description>Bram Stoker's Dracula (USA)</description>
			<year>1992</year>
			<publisher>Sony Imagesoft</publisher>
			<info name="serial" value="T-93065"/>
			<info name="ring_code" value="CDAC-020100 4"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="bram stoker's dracula (usa)" sha1="35a46f2a7c32d18ec22e3e8a7c03518f915fb4b2" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="draculaa" cloneof="dracula">
			<description>Bram Stoker's Dracula (USA, Alt)</description>
			<year>1992</year>
			<publisher>Sony Imagesoft</publisher>
			<info name="serial" value="T-93065"/>
			<info name="ring_code" value="CDAC-050100 1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="bram stoker's dracula (usa) (alt)" sha1="98ef333e37ed4968c3421966f36ea158a5a3e203" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="brutal">
			<description>Brutal - Paws of Fury (USA)</description>
			<year>1994</year>
			<publisher>GameTek</publisher>
			<info name="serial" value="T-83015"/>
			<info name="ring_code" value="SEGAT830155 R1D MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="brutal - paws of fury (usa)" sha1="4e3f09cb9f1ce381adcf0b832a4d9683e75dd8b5" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="cliffh">
			<description>Cliffhanger (USA)</description>
			<year>1993</year>
			<publisher>Sony Imagesoft</publisher>
			<info name="serial" value="T-93075"/>
			<info name="ring_code" value="CDAC-053600 1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="cliffhanger (usa)" sha1="71753bdebddc8de1f9920f19e06a7858a470f286" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="cobracom">
			<description>Cobra Command (USA)</description>
			<year>1992</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4402"/>
			<info name="ring_code" value="CDAC-031400 5"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="cobra command (usa)" sha1="2d7c32591cec389f6d5feb5f0301495ff8021307" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="corpse32" cloneof="corpse">
			<description>Corpse Killer (USA, 32X)</description>
			<year>1994</year>
			<publisher>Digital Pictures</publisher>
			<info name="serial" value="T-162055"/>
			<info name="ring_code" value="GW 02361 RE-1 SRCR##03"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="corpse killer (usa) (32x)" sha1="68a6c75bc730025e90fa413c107090e7f4e377e0" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="darkwiz">
			<description>Dark Wizard (USA)</description>
			<year>1994</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4651"/>
			<info name="ring_code" value="CDAC-059200 3"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="dark wizard (usa)" sha1="cf784af53b6dedc2777b91f5ac5f169f2f7b9c30" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="dblswtch">
			<description>Double Switch (USA)</description>
			<year>1993</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4419"/>
			<info name="ring_code" value="CDAC-052900 1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="double switch (usa)" sha1="2b727773fda836ddfb972dc98820bee7135da709" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="ecco2">
			<description>Ecco - The Tides of Time (USA)</description>
			<year>1993</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4441"/>
			<info name="ring_code" value="CDAC 077400"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="ecco - the tides of time (usa)" sha1="20cb72bf75a848568dd034188bebe316138b6186" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="ecco">
			<description>Ecco the Dolphin (USA)</description>
			<year>1996?</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4408"/>
			<info name="ring_code" value="CDAC-042000 3, CDAC-042000 1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="ecco the dolphin (usa)" sha1="7fb88d4f0fe34ee40991d724b9e90f7586081fd2" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="espnbb">
			<description>ESPN Baseball Tonight (USA)</description>
			<year>1993</year>
			<publisher>Sony Imagesoft</publisher>
			<info name="serial" value="T-93115"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="espn baseball tonight (usa)" sha1="3965f3f96579abe6d754360fb123f5cfb2e8cce1" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="eternalc">
			<description>Eternal Champions - Challenge from the Dark Side (USA)</description>
			<year>1994</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4427"/>
			<info name="ring_code" value="SEGA4427 R1J 11"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="eternal champions - challenge from the dark side (usa)" sha1="9df55bc7e446080684f35b1af5aa570b67a47f84" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="ffightcd">
			<description>Final Fight CD (USA)</description>
			<year>1993</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4410"/>
			<info name="ring_code" value="CDAC-041400 6, CDAC-041400 4"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="final fight cd (usa)" sha1="bd0ae447a302d2e220f13c84a7a56a45007c7e83" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="gztexas">
			<description>Ground Zero Texas (USA)</description>
			<year>1993</year>
			<publisher>Sony Imagesoft</publisher>
			<info name="ring_code" value="005320-CDAC (Disc 2)"/>
			<info name="serial" value="T-93145"/>
			<part name="cdrom1" interface="scd_cdrom">
				<feature name="part_id" value="Disc 1" />
				<diskarea name="cdrom">
					<disk name="ground zero texas (1993)(sony imagesoft)(ntsc)(us)(disc 1 of 2)[!]" sha1="cb019a26b3edec7a8f0119d74a0991aa5b258313" writeable="no"/>
				</diskarea>
			</part>
			<part name="cdrom2" interface="scd_cdrom">
				<feature name="part_id" value="Disc 2" />
				<diskarea name="cdrom">
					<disk name="ground zero texas (usa) (disc 2)" sha1="84d79bb8cfc7f30809f7b31e794227b449a40037" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="hota">
			<description>Heart of the Alien - Out of this World Parts I and II (USA, RE)</description>
			<year>1994</year>
			<publisher>Virgin Interactive</publisher>
			<info name="serial" value="T-70025"/>
			<info name="ring_code" value="HOTALIENRE R1H MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="heart of the alien - out of this world parts i and ii (usa) (re)" sha1="a2784fa95bb3b29067b5d8148dd95877456577e7" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="ironhlx">
			<description>Iron Helix (USA)</description>
			<year>1994</year>
			<publisher>Spectrum Holobyte</publisher>
			<info name="serial" value="T-124015"/>
			<info name="ring_code" value="SEGAT124015 R2H MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="iron helix (usa)" sha1="243a1c1691ab1a587371e34c1692663b28814184" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="jpark">
			<description>Jurassic Park (USA)</description>
			<year>1994</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4410"/>
			<info name="ring_code" value="SEGA4411RE R4C MFD BY JVC, SEGA4411RE R3C MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="jurassic park (usa)" sha1="8ab39eda898277571127b9ac03dce64546602caf" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="lethalen">
			<description>Lethal Enforcers (USA)</description>
			<year>1994</year>
			<publisher>Konami</publisher>
			<info name="serial" value="T-95015"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="lethal enforcers (usa)" sha1="2a9bb24ed2a7db353e035311269180b368230069" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="lunar">
			<description>Lunar - The Silver Star (USA)</description>
			<year>1993</year>
			<publisher>Working Designs</publisher>
			<info name="serial" value="T-95015"/>
			<info name="ring_code" value="SEGAT127015RE R1C MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="lunar - the silver star (usa)" sha1="eebcd9cdadb0a74de4313fc44fff83ba95ba3135" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="mansion">
			<description>Mansion of Hidden Souls (USA)</description>
			<year>1994</year>
			<publisher>Vic Tokai</publisher>
			<info name="serial" value="T-23015"/>
			<info name="ring_code" value="SEGAT23015 R1D MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="mansion of hidden souls (usa)" sha1="1d1dba770de6d5969d23d2e86ad4028445d514c4" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="mk">
			<description>Mortal Kombat (USA)</description>
			<year>1993</year>
			<publisher>Arena</publisher>
			<info name="serial" value="T-81025"/>
			<info name="ring_code" value="CDCA-061500 2, CDCA-060900 3"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="mortal kombat (usa)" sha1="454e23c8922380f813a3a5b9d94902a691109332" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="nhl94">
			<description>NHL '94 (USA)</description>
			<year>1993</year>
			<publisher>Electronic Arts</publisher>
			<info name="serial" value="T-50015"/>
			<info name="ring_code" value="CDAC-056700 2"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="nhl '94 (usa)" sha1="ac34c65117668dc53e7075a0dbe9bd260fdb1c15" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="ntrap32" cloneof="ntrap">
			<description>Night Trap (USA, 32X)</description>
			<year>1994</year>
			<publisher>Digital Pictures</publisher>
			<info name="serial" value="T-16202F"/>
			<info name="ring_code" value="GW 00161.1 RE-1 SRCR##02 (Disc 1), GW 00161.2 RE-1 SRCR##02 (Disc 2)"/>
			<part name="cdrom1" interface="scd_cdrom">
				<feature name="part_id" value="Disc 1" />
				<diskarea name="cdrom">
					<disk name="night trap (usa) (disc 1) (32x)" sha1="a4407b3264ef29d343f7d4b984194bc4636009d3" writeable="no"/>
				</diskarea>
			</part>
			<part name="cdrom2" interface="scd_cdrom">
				<feature name="part_id" value="Disc 2" />
				<diskarea name="cdrom">
					<disk name="night trap (usa) (disc 2) (32x)" sha1="18b2a72bf91589ef43986b3f3add9b70c609f346" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="ntrap">
			<description>Night Trap (USA)</description>
			<year>1994</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4903"/>
			<info name="ring_code" value="CDRM-1027400 5 (Disc 1), CDRM-1027410 2, CDRM-1027410 1 (Disc 2)"/>
			<part name="cdrom1" interface="scd_cdrom">
				<feature name="part_id" value="Disc 1" />
				<diskarea name="cdrom">
					<disk name="night trap (usa) (disc 1)" sha1="c2c18c6af2aae9619ca5772fcb6aecc79a142a40" writeable="no"/>
				</diskarea>
			</part>
			<part name="cdrom2" interface="scd_cdrom">
				<feature name="part_id" value="Disc 2" />
				<diskarea name="cdrom">
					<disk name="night trap (usa) (disc 2)" sha1="41c44780c325403d9c4522fc3d010912fc3dad5a" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="pitfall">
			<description>Pitfall - The Mayan Adventure (USA)</description>
			<year>1994</year>
			<publisher>Activision</publisher>
			<info name="serial" value="T-130025"/>
			<info name="ring_code" value="SEGAT130025 R1H MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="pitfall - the mayan adventure (usa)" sha1="512f8ebf40e653f82ac9528193344ad990b58bf3" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="ppersia">
			<description>Prince of Persia (USA)</description>
			<year>1993</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4652"/>
			<info name="ring_code" value="CDAC-032200 6"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="prince of persia (usa)" sha1="fd9250f32c23e0954b197d1833c20de705df43d3" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="puggsy">
			<description>Puggsy (USA)</description>
			<year>1993</year>
			<publisher>Psygnosis</publisher>
			<info name="serial" value="T-113035"/>
			<info name="ring_code" value="CDAC-053800 2"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="puggsy (usa)" sha1="307206f9f4154699e9386fa9b45bd79d5ed72e5d" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="revninja">
			<description>Revenge of the Ninja (USA)</description>
			<year>1993</year>
			<publisher>Renovation</publisher>
			<info name="serial" value="T-49035"/>
			<info name="ring_code" value="SEGAT49035 R1C MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="revenge of the ninja (usa)" sha1="d6f0a13f1b630ba771cad7c86b607f31cf6092b7" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="risedrg">
			<description>Rise of the Dragon (USA)</description>
			<year>1994</year>
			<publisher>Dynamix</publisher>
			<info name="serial" value="T-110035"/>
			<info name="ring_code" value="S604430RE R1D MFD BY JVC, S604430RE R2D MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="rise of the dragon (usa)" sha1="412d819633740c597b67591cf12fdac7c7081194" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="risedrga" cloneof="risedrg">
			<description>Rise of the Dragon (USA, Alt)</description>
			<year>1994</year>
			<publisher>Dynamix</publisher>
			<info name="serial" value="T-110035"/>
			<info name="ring_code" value="CDAC-040300 1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="rise of the dragon (usa) (alt)" sha1="e84d20447bec4c5bed1bfe27372c5a927d5fbdb2" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="sshark">
			<description>Sewer Shark (USA)</description>
			<year>1992</year>
			<publisher>Sony Imagesoft</publisher>
			<info name="serial" value="T-93015"/>
			<info name="ring_code" value="CDRM-1033200 2"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="sewer shark (usa)" sha1="0f339806d73c473c20906935836d49457339430f" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="ssharkb" cloneof="sshark">
			<description>Sewer Shark (USA, Bundle)</description>
			<year>1992</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4101"/>
			<info name="ring_code" value="CDRM-1095270 2"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="sewer shark (usa) (bundle)" sha1="b5cd7913425b5f14c7fd6a5df9dc66a40022edc6" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="ssharkba" cloneof="sshark">
			<description>Sewer Shark (USA, Bundle, Alt)</description>
			<year>1992</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4101"/>
			<info name="ring_code" value="610-5574P-00086 1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="sewer shark (usa) (bundle) (alt)" sha1="0353015285afb2fa5119b3e700725d6b8e46d680" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="holmes2">
			<description>Sherlock Holmes - Consulting Detective Vol. II (USA)</description>
			<year>1994</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4653"/>
			<info name="ring_code" value="CDAC-041000 1 (Disc 1), CDAC-041100 2 (Disc 2)"/>
			<part name="cdrom1" interface="scd_cdrom">
				<feature name="part_id" value="Disc 1" />
				<diskarea name="cdrom">
					<disk name="sherlock holmes - consulting detective vol ii (usa) (disc 1)" sha1="162af0ed791b8a18040ecb3925984a738dc72d49" writeable="no"/>
				</diskarea>
			</part>
			<part name="cdrom2" interface="scd_cdrom">
				<feature name="part_id" value="Disc 2" />
				<diskarea name="cdrom">
					<disk name="sherlock holmes - consulting detective vol ii (usa) (disc 2)" sha1="3de4f89de8920185197d8a65f0ea97a83e774a98" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="shinfrce">
			<description>Shining Force CD (USA)</description>
			<year>1994</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4656"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="shining force cd (usa)" sha1="ddd94e30ba53faf04336b5854dd4e0d9980067b5" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="shinfrcea" cloneof="shinfrce">
			<description>Shining Force CD (USA, Alt)</description>
			<year>1994</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4656"/>
			<info name="ring_code" value="3/95 6RA3 1008604656, 3/95 5RA1 1008604656"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="shining force cd (usa) (alt)" sha1="ddb304849d01df44251d69b890df47c8db1d8642" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="silpheed">
			<description>Silpheed (USA)</description>
			<year>1993</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4423"/>
			<info name="ring_code" value="SEGA4423 R2D MFD BY JVC, SEGA4423RE R2D MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="silpheed (usa)" sha1="f4d368f13f7998fb8d37c9a3439d42497e0ee359" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="soniccd">
			<description>Sonic CD (USA)</description>
			<year>1993</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4407"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="sonic cd (usa)" sha1="ae08e06cc13b49b75c45e69334b2bdea4974454f" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="swra">
			<description>Star Wars - Rebel Assault (USA)</description>
			<year>1994</year>
			<publisher>JVC</publisher>
			<info name="serial" value="T-60075"/>
			<info name="ring_code" value="SEGAT60075 R1D MFD BY JVC, SEGAT60075 R2C MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="star wars - rebel assault (usa)" sha1="f1049ddf315f3a9ecd29378bc026a05669120112" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="stellarf">
			<description>Stellar-Fire (USA)</description>
			<year>1993</year>
			<publisher>Dynamix</publisher>
			<info name="serial" value="T-110025"/>
			<info name="ring_code" value="SEGAT11025 R1D MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="stellar-fire (usa)" sha1="4e0245e30cac825c262551eda322eb774919e87b" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="timegal">
			<description>Time Gal (USA)</description>
			<year>1993</year>
			<publisher>Renovation</publisher>
			<info name="serial" value="T-6214"/>
			<info name="ring_code" value="SEGAT49025 R2C MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="time gal (usa)" sha1="22c4bc9adb5560c276f0fe88967e04bf279d54d0" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="tcataly">
			<description>Tomcat Alley (USA)</description>
			<year>1994</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4429"/>
			<info name="ring_code" value="1008604429 9/95 1RA1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="tomcat alley (usa)" sha1="b90a1fcdd7371da1c36591b53264e809637b0a18" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="wheelfor">
			<description>Wheel of Fortune (USA)</description>
			<year>1994</year>
			<publisher>Sony Imagesoft</publisher>
			<info name="serial" value="T-93085"/>
			<info name="ring_code" value="CDAC-077500 1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="wheel of fortune (usa)" sha1="1c48a4dd3d70ed9d4450aea57bb5dc671e5c4a4c" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="whoshot">
			<description>Who Shot Johnny Rock? (USA)</description>
			<year>1994</year>
			<publisher>American Laser Games</publisher>
			<info name="serial" value="T-111045"/>
			<info name="ring_code" value="SEGAT111045 R1H MFD BY JVC"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="who shot johnny rock (usa)" sha1="dc9675c0bfc19baae5be13ce1540062c09b930f3" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="3ninja">
			<description>3 Ninjas Kick Back (USA)</description>
			<year>1994</year>
			<publisher>Sony Imagesoft</publisher>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="3 ninjas kick back (1994)(sony imagesoft)(ntsc)(us)[!]" sha1="772ab6cba658e9851d6ead099e0100a21860228f" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="wilybeam">
			<description>The Adventures of Willy Beamish (USA)</description>
			<year>1993</year>
			<publisher>Dynamix</publisher>
			<info name="serial" value="T-6300"/>
			<info name="ring_code" value="CDAC-036400 1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="adventures of willy beamish, the (1993)(dynamix)(us)[!][cdac-036400 1]" sha1="6a74c3bc80d53ab427eee8dc19b9b66b017fd9f1" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="spidking">
			<description>The Amazing Spider-Man vs. The Kingpin (USA)</description>
			<year>1993</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4412"/>
			<info name="ring_code" value="CDAC-047100 6"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="amazing spider-man vs. the kingpin, the (1993)(sega)(ntsc)(us)[!][cdac-047100 6]" sha1="050812db19ca35a1db549c18445d580c627c1e82" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="batmanrn">
			<description>Batman Returns (USA)</description>
			<year>1993</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4401"/>
			<info name="ring_code" value="CDAC-040500 1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="batman returns (1993)(sega)(ntsc)(us)[!][cdac-040500 1]" sha1="15006b43f116d4e4d85ae335bddb4f6c70288c47" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="blackh">
			<description>Blackhole Assault (USA)</description>
			<year>1993</year>
			<publisher>Bignet</publisher>
			<info name="serial" value="T-6400"/>
			<info name="ring_code" value="CDAC-031700 2"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="blackhole assault (1993)(bignet)(ntsc)(us)[!][cdac-031700 2]" sha1="7b3e4027715b8752579ad862ac19daae50eb34ea" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="blackha" cloneof="blackh">
			<description>Blackhole Assault (USA, Alt)</description>
			<year>1993</year>
			<publisher>Bignet</publisher>
			<info name="serial" value="T-6400"/>
			<info name="ring_code" value="CDAC-031700 1"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="blackhole assault (1993)(bignet)(ntsc)(us)[!][cdac-031700 1]" sha1="584c78a01a136368d7f20b43a6eddb81674dd932" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="bouncers">
			<description>Bouncers (USA)</description>
			<year>1994</year>
			<publisher>Sega</publisher>
			<info name="serial" value="4908"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="bouncers (1994)(sega)(ntsc)(us)[!]" sha1="0e7e23e6b31eaf8e70ae88ce0f5324ce89f12717" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="draculab" cloneof="dracula">
			<description>Bram Stoker's Dracula (USA, v2.0)</description>
			<year>1993</year>
			<publisher>Sony Imagesoft</publisher>
			<info name="serial" value="T-93065"/>
			<part name="cdrom" interface="scd_cdrom">
				<diskarea name="cdrom">
					<disk name="bram stoker's dracula v2.0 (1993)(sony imagesoft)(ntsc)(us)[!]" sha1="b358e43e94ddd1eea7244f8288c8ad33c083f5a1" writeable="no"/>
				</diskarea>
			</part>
		</software>
		<software name="dino2">